name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_runner_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: build docker image 
        run: DOCKER_BUILDKIT=1 docker build -f Dockerfile -t ghcr.io/${{ github.actor }}/actions_runner:ubuntu2204 .
      - name: push docker image 
        run: env && docker push ghcr.io/${{ github.actor }}/actions_runner:ubuntu2204
